[package]
name = "bitcoin-donation"
version = "0.1.0"
authors = ["Cooper Paul EdenDay <cedenday@protonmail.com>"]

[dependencies]
serde = { version = "^1.0.11", features = ["derive"] }
serde_json = "^1.0.2"
